image: java:8

before_script:
    - chmod +x gradlew

# We redirect the gradle user home using -g so that it caches the
# wrapper and dependencies.
# https://docs.gradle.org/current/userguide/gradle_command_line.html
#
# Unfortunately it also caches the build output so
# cleaning removes reminants of any cached builds.
# The assemble task actually builds the project.
# If it fails here, the tests can't run.
build:
  stage: build
  script:
    - ./gradlew -g /cache/.gradle clean assemble
  allow_failure: false
  tags:
    - gradle

# Use the generated build output to run the tests.
test:
  stage: test
  script:
    - ./gradlew -g /cache/.gradle check
  tags:
    - gradle

jar:
  stage: deploy
  script:
    - ./gradlew -g /cache/.gradle jar
  artifacts:
    paths:
      - core/build/libs/core-1.0-SNAPSHOT.jar
      - client/build/libs/client-1.0-SNAPSHOT.jar
      - server/build/libs/server-1.0-SNAPSHOT.jar
  tags:
    - gradle

pages:
  stage: deploy
  script:
    - ./gradlew -g /cache/.gradle javadoc
  artifacts:
    paths:
      - core/build/docs/javadoc
      - client/build/docs/javadoc
      - server/build/docs/javadoc
  only:
    - master
    - dev
  tags:
    - gradle
